name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: rustup update --no-self-update stable
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verborse
        
  code-style:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: rustup update --no-self-update stable
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all     
